force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Party__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <label>Party Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Party__c/fields/PartyCode__c.field-meta.xml
<CustomField>
    <fullName>PartyCode__c</fullName>
    <label>PartyCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PartyControllerTest.cls
@isTest
public class PartyControllerTest {
    @isTest
    static void testGetAllParties() {
        Party__c party = new Party__c(Party_Name__c='Green Alliance', Description__c='A progressive environmental party', PartyCode__c='GA');
        insert party;

        List<Party__c> parties = PartyController.getAllParties();
        System.assertNotEquals(0, parties.size(), 'Expected parties to be returned');
        System.assertEquals('Green Alliance', parties[0].Party_Name__c, 'Expected name to match inserted party');
    }
}